# Specify version format
version: "{build}"

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  BUILD_EXAMPLES: OFF  # don't build examples to not exceed allowed build time (40 min)
  BUILD_TUTORIALS: OFF  # don't build tutorials to not exceed allowed build time (40 min)
  CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE="C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  BUILD_CORE_ONLY: ON
  matrix:
    - image: Visual Studio 2017
      platform: x64
      CMAKE_GENERATOR: -G"Visual Studio 15 2017 Win64"
  
    - image: Visual Studio 2015
      platform: x64
      CMAKE_GENERATOR: -G"Visual Studio 15 2015 Win64"
      
# build configuration, i.e. Debug, Release, etc.
configuration:
  #- Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\dart

# scripts that run after cloning repository
install:
  - if "%platform%"=="Win32" set VCPKG_ARCH=x86-windows
  - if "%platform%"=="x64"   set VCPKG_ARCH=x64-windows
  
  # install pacakges
  # ---- required dependencies: boost, eigen3, libccd, fcl, assimp
  - vcpkg install boost:%VCPKG_ARCH%
  - vcpkg install eigen3:%VCPKG_ARCH%
  - vcpkg install ccd:%VCPKG_ARCH%
  - vcpkg install fcl:%VCPKG_ARCH%
  - vcpkg install assimp:%VCPKG_ARCH%
  # ---- optional dependencies: nlopt, ipopt, bullet3, ode, flann, tinyxml2, urdfdom_headers, urdfdom, opengl, freeglut, osg
  #- vcpkg install nlopt:%VCPKG_ARCH%
  #- vcpkg install ipopt:%VCPKG_ARCH%
  #- vcpkg install bullet3:%VCPKG_ARCH%
  #- vcpkg install ode:%VCPKG_ARCH%
  #- vcpkg install flann:%VCPKG_ARCH%
  #- vcpkg install tinyxml2:%VCPKG_ARCH%
  #- vcpkg install urdfdom_headers:%VCPKG_ARCH%
  #- vcpkg install urdfdom:%VCPKG_ARCH%
  #- vcpkg install opengl:%VCPKG_ARCH%
  #- vcpkg install freeglut:%VCPKG_ARCH%
  #- vcpkg install osg:%VCPKG_ARCH%
  
  - vcpkg integrate install
  

# scripts to run before build
before_build:
  - cmd: cd C:\projects\dart
  - cmd: md build
  - cmd: cd build
  - cmd: cmake %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%configuration% -DBUILD_CORE_ONLY="%BUILD_CORE_ONLY%" -DDART_BUILD_EXAMPLES="%BUILD_EXAMPLES%" -DDART_BUILD_TUTORIALS="%BUILD_TUTORIALS%" -DDART_MSVC_DEFAULT_OPTIONS="%MSVC_DEFAULT_OPTIONS%" %CMAKE_TOOLCHAIN_FILE% ..

# preserve contents of selected directories and files across project builds
cache:
  - C:\tools\vcpkg\installed -> .appveyor.yml
  - C:\tools\vcpkg\packages -> .appveyor.yml

build:
  project: C:\projects\dart\build\dart.sln # path to Visual Studio solution or project
  parallel: true                           # enable MSBuild parallel builds
  verbosity: quiet                         # MSBuild verbosity level (quiet|minimal|normal|detailed)

test_script:
  - cmd: ctest --build-config %configuration% --parallel 4 --output-on-failure
